networks:
  inceptionnet:
#     driver: bridge
    name: inceptionnet

volumes:
  wordpress_data:
#     driver: local
#     driver_opts:
#       type: none
#       device: /Users/otuyishi/data/wordpress_data
#       o: bind
#   mariadb_data:
#     driver: local
#     driver_opts:
#       type: none
#       device: /Users/otuyishi/data/mariadb_data
#       o: bind

services:
#   mariadb:
#     build:
#       context: ./requirements/mariadb
#       dockerfile: Dockerfile.mariadb
#     container_name: mariadb
#     image: mariadb
#     environment:
#       DATABASE_NAME: ${DB_NAME}
#       DATABASE_USERNAME: ${DB_USERNAME}
#       DATABASE_PASSWORD: ${DATABASE_PASSWORD}
#       DATABASE_HOST: ${DATABASE_HOST}
#     volumes:
#       - mariadb_data:/var/lib/mysql
#     networks:
#       - inceptionnet
#     restart: always
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost"]
#       interval: 5s
#       timeout: 5s
#       retries: 77

  wordpress:
    build: ./requirements/wordpress/.
#       context: ./requirements/wordpress
#       dockerfile: Dockerfile.wordpress
    container_name: wordpress
    image: wordpress
#     env_file:
#       - .env
    volumes:
      - wordpress_data:/var/www/html
#     environment:
#       DATABASE_NAME: ${DB_NAME}
#       DATABASE_PASSWORD: ${DATABASE_PASSWORD}
#       DATABASE_USERNAME: ${DB_USERNAME}
#       DATABASE_HOST: ${DATABASE_HOST}
#       WORDPRESS_ADMIN_NAME: ${WORDPRESS_ADMIN_NAME}
#       WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
#       WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
#     # depends_on:
#     #   mariadb:
#     #     condition: service_healthy
    networks:
      - inceptionnet
#     restart: always
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost"]
#       interval: 5s
#       timeout: 5s
#       retries: 77

  nginx:
    build: ./requirements/nginx/.
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "443:443"
    # depends_on:
    #   wordpress:
    #     condition: service_healthy
    networks:
      - inceptionnet
    restart: always
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost"]
      # interval: 5s
      # timeout: 5s
      # retries: 77
