services:
  mariadb:
    build: ./requirements/mariadb/.
    container_name: mariadb
    image: mariadb:10.5.23
    env_file:
      - .env
    environment:
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
    volumes:
      - mariadb_auto:/var/lib/mysql
    networks:
      - inceptionnet
    restart: always
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 100

  wordpress:
    build: ./requirements/wordpress/.
    container_name: wordpress
    image: wordpress
    env_file:
      - .env
    volumes:
      - ./data/wordpress/:/var/www/html
    environment:
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_ADMIN_NAME: ${WORDPRESS_ADMIN_NAME}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
    depends_on:
      - mariadb
        # condition: service_healthy
    networks:
      - inceptionnet
    restart: always
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 100

  nginx:
    build: ./requirements/nginx/.
    container_name: nginx
    image: nginx
    volumes:
      - ./data/wordpress/:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wordpress
        # condition: service_healthy
    networks:
      - inceptionnet
    restart: always
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 100

networks:
  inceptionnet:
    driver: bridge
    name: inceptionnet

volumes:
  mariadb_auto:
#   mariadb:
#    name: ${MARIADB_DATABASE}
#    driver_opts:
#     type: none
#     device: /home/otuyishi/data/mariadb
#     o: bind
    
#   wordpress:
#    name: ${WORDPRESS_DB_NAME}
#    driver_opts:
#     type: none
#     device: /home/otuyishi/data/wordpress
#     o: bind