version: '3.7'

services:
  mariadb:
    build: ./requirements/mariadb/.
    container_name: mariadb
    image: mariadb:10.5.23
    env_file:
      - .env
    environment:
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inceptionnet
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 2s

  wordpress:
    build: ./requirements/wordpress/.
    container_name: wordpress
    image: wordpress
    env_file:
      - .env
    volumes:
      - wordpress-data:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_ADMIN_NAME: ${WORDPRESS_ADMIN_NAME}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inceptionnet
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 10
    #   start_period: 2s

  nginx:
    build: ./requirements/nginx/.
    container_name: nginx
    image: nginx
    volumes:
      - wordpress-data:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wordpress
      # wordpress:
      #   condition: service_healthy
    networks:
      - inceptionnet
    restart: always

networks:
  inceptionnet:
    name: inceptionnet

volumes:
  mariadb-data:
    name: mariadb-data
  wordpress-data:
    name: wordpress-data
