services:
  mariadb:
    build: ./requirements/mariadb/.
    container_name: mariadb
    image: mariadb:10.5.23
    environment:
      DATABASE_NAME: ${DB_NAME}
      DATABASE_USERNAME: ${DB_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
    volumes:
      - ./mariadb/data/:/var/lib/mysql
    networks:
      - inceptionnet
    restart: always
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 100

  wordpress:
    build: ./requirements/wordpress/.
    container_name: wordpress
    image: wordpress
    env_file:
      - .env
    volumes:
      - ./wordpress/data/:/var/www/html
    environment:
      DATABASE_NAME: ${DB_NAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USERNAME: ${DB_USERNAME}
      DATABASE_HOST: ${DATABASE_HOST}
      WORDPRESS_ADMIN_NAME: ${WORDPRESS_ADMIN_NAME}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
    depends_on:
      - mariadb
        # condition: service_healthy
    networks:
      - inceptionnet
    restart: always
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 100

  nginx:
    build: ./requirements/nginx/.
    container_name: nginx
    image: nginx
    volumes:
      - ./wordpress/data/:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wordpress
        # condition: service_healthy
    networks:
      - inceptionnet
    restart: always
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 100

networks:
  inceptionnet:
    driver: bridge
    name: inceptionnet
