FROM debian:12.0

RUN apt-get update && \
	apt-get install -y mariadb-server mariadb-client

COPY tools/setup_mdb.sh /usr/local/bin/setup_mdb.sh
COPY tools/mdb_init.sql /usr/local/bin/mdb_init.sql

RUN chmod +x /usr/local/bin/setup_mdb.sh && \
    chmod +x /usr/local/bin/mdb_init.sql

EXPOSE 3306

CMD ["bash", "-c", "/usr/local/bin/setup_mdb.sh && exec mysqld_safe"]
