#docker-Compose version
version: '3.8'

#services will tell us different services(containers) that are being used
services:
  wordpress:
    #build specifies how to build docker image for this services 
    build:
      context: .
      dockerfile: Dockerfile.wordpress
    volumes:
      - ./tools:/tools
      - ./conf:/conf
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    depends_on:
      - mariadb

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./conf:/conf
    ports:
      - "443:443"
    depends_on:
      - wordpress

  mariadb:
    build:
      context: .
      dockerfile: Dockerfile.mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./tools:/tools
      - ./requirements:/requirements

volumes:
  db_data:
