FROM debian:12.0

RUN apt-get update && \
    apt-get install -y mariadb-server mariadb-client

WORKDIR /tools

COPY ./tools/setup_mdb.sh /tools/setup_mdb.sh
COPY ./tools/mdb_init.sql /tools/mdb_init.sql

RUN chmod +x /tools/setup_mdb.sh

CMD ["/tools/setup_mdb.sh"]
