CREATE USER '$WORDPRESS_DB_USER'@'$WORDPRESS_DB_HOST' IDENTIFIED BY '$WORDPRESS_USER_PASSWORD';
CREATE DATABASE $WORDPRESS_DB_NAME;
GRANT ALL PRIVILEGES ON \`$WORDPRESS_DB_NAME\`.* TO '$WORDPRESS_DB_USER'@'$WORDPRESS_DB_HOST';
ALTER USER 'root'@'localhost' IDENTIFIED BY '$WORDPRESS_ADMIN_PASSWORD';
FLUSH PRIVILEGES;
