-- to start MariaDB service
rc-services mariadb start

FLUSH PRIVILEGES;
SET PASSWORD FOR 'root'@'localhost' = PASSWORD('$DB_ROOT_PASSWORD');

CREATE DATABASE IF NOT EXISTS '$DB_NAME';
CREATE USER IF NOT EXISTS '$DB_USERNAME'@'localhost';
CREATE USER IF NOT EXISTS '$DB_USERNAME'@'%';
SET PASSWORD FOR '$DB_USERNAME'@'localhost' = PASSWORD('$DATABASE_PASSWORD');
SET PASSWORD FOR '$DB_USERNAME'@'%' = PASSWORD('$DATABASE_PASSWORD');
GRANT ALL PRIVILEGES ON '$DB_NAME'.* TO '$DB_USERNAME'@'localhost';
GRANT ALL PRIVILEGES ON '$DB_NAME'.* TO '$DB_USERNAME'@'%';
FLUSH PRIVILEGES;

-- to stop MariaDB service
rc-services mariadb stop
