CREATE USER 'wpuser'@'%' IDENTIFIED BY '12345';
GRANT ALL PRIVILEGES ON 'wordpress'.* TO 'wpuser'@'%'WITH GRANT OPTION;
FLUSH PRIVILEGES;
CREATE DATABASE IF NOT EXISTS 'wordpress';
SET PASSWORD FOR 'root'@'%' = PASSWORD('1234');
FLUSH PRIVILEGES;
