#!/bin/bash

# CREATE USER '$WORDPRESS_DB_USER'@'%' IDENTIFIED BY '$WORDPRESS_USER_PASSWORD';
# CREATE DATABASE $WORDPRESS_DB_NAME;
# GRANT ALL PRIVILEGES ON \`$WORDPRESS_DB_NAME\`.* TO '$WORDPRESS_DB_USER'@'%';
# ALTER USER 'root'@'localhost' IDENTIFIED BY '$WORDPRESS_ADMIN_PASSWORD';
# FLUSH PRIVILEGES;

echo "FLUSH PRIVILEGES;
	CREATE DATABASE IF NOT EXISTS \`${WORDPRESS_DB_NAME}\`;
	CREATE USER IF NOT EXISTS '${WORDPRESS_DB_USER}'@'%' IDENTIFIED BY '${WORDPRESS_DB_PASSWORD}';
	GRANT ALL PRIVILEGES on \`${WORDPRESS_DB_NAME}\`.* TO '${WORDPRESS_DB_USER}'@'%';
	FLUSH PRIVILEGES;" > /etc/mysql/mdb_init.sql

exec mariadbd --user=mysql
