#!/bin/bash

# : "${WORDPRESS_DB_USER:?WORDPRESS_DB_USER must be set}"
# : "${WORDPRESS_DB_HOST:?WORDPRESS_DB_HOST must be set}"
# : "${WORDPRESS_USER_PASSWORD:?WORDPRESS_USER_PASSWORD must be set}"
# : "${WORDPRESS_DB_NAME:?WORDPRESS_DB_NAME must be set}"
# : "${WORDPRESS_ADMIN_PASSWORD:?WORDPRESS_ADMIN_PASSWORD must be set}"

# Commands to execute with environment variables
mysql << EOF
CREATE USER '$WORDPRESS_DB_USER'@'$WORDPRESS_DB_HOST' IDENTIFIED BY '$WORDPRESS_USER_PASSWORD';
CREATE DATABASE '$WORDPRESS_DB_NAME';
GRANT ALL PRIVILEGES ON \`$WORDPRESS_DB_NAME\`.* TO '$WORDPRESS_DB_USER'@'$WORDPRESS_DB_HOST';
ALTER USER 'root'@'localhost' IDENTIFIED BY '$WORDPRESS_ADMIN_PASSWORD';
FLUSH PRIVILEGES;
EOF


# service mariadb start 