FROM debian:12.0

RUN apt-get update && apt-get install -y php8.2 php8.2-cli php8.2-common php8.2-imap php8.2-redis php8.2-snmp php8.2-xml php8.2-mysqli php8.2-zip php8.2-mbstring php8.2-curl libapache2-mod-php


CMD ["/bin/bash"]
